export const styles = {
  "& .rbc-calendar": {
    fontFamily: "'Inter', sans-serif",
    fontSize: "13px",
    color: "#111827",
    bg: "white",
    border: "1px solid #E5E7EB",
    borderRadius: "12px",
    overflow: "hidden",
    height: "calc(100vh - 150px - 48px)",
    minHeight: "500px",
    display: "flex",
    flexDirection: "column",
  },

  "& .rbc-toolbar": {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    px: "20px",
    py: "14px",
    borderBottom: "1px solid #E5E7EB",
    mb: 0,
    gap: "12px",
    flexWrap: "nowrap",
  },
  "& .rbc-toolbar .rbc-toolbar-label": {
    fontSize: "16px",
    fontWeight: "600",
    color: "#111827",
    flex: 1,
    textAlign: "left",
    px: "8px",
  },
  "& .rbc-toolbar button": {
    fontSize: "13px",
    fontWeight: "500",
    color: "#6B7280",
    bg: "transparent",
    border: "1px solid #E5E7EB",
    borderRadius: "6px",
    px: "10px",
    py: "5px",
    cursor: "pointer",
    lineHeight: 1,
    transition: "all 150ms ease",
    _hover: { bg: "#F3F4F6", color: "#111827", borderColor: "#D1D5DB" },
    _focus: { outline: "none", boxShadow: "0 0 0 2px #BFDBFE" },
  },
  "& .rbc-btn-group": { display: "flex", gap: "4px" },
  "& .rbc-btn-group:last-of-type": {
    bg: "#F3F4F6",
    borderRadius: "8px",
    p: "3px",
    gap: "2px",
    border: "none",
  },
  "& .rbc-btn-group:last-of-type button": {
    border: "none",
    borderRadius: "6px",
    px: "14px",
    py: "5px",
    fontSize: "13px",
    fontWeight: "500",
    color: "#6B7280",
    bg: "transparent",
    _hover: {
      bg: "white",
      color: "#111827",
      border: "none",
      boxShadow: "none",
    },
  },
  "& .rbc-btn-group:last-of-type button.rbc-active": {
    bg: "#4F46E5",
    color: "white",
    border: "none",
    boxShadow: "none",
    _hover: { bg: "#4338CA", color: "white" },
  },

  "& .rbc-header": {
    px: "12px",
    py: "10px",
    fontSize: "12px",
    fontWeight: "500",
    color: "#6B7280",
    textAlign: "center",
    bg: "white",
    borderBottom: "1px solid #E5E7EB",
    borderLeft: "1px solid #E5E7EB",
  },
  "& .rbc-header:first-of-type": { borderLeft: "none" },
  "& .rbc-header a": {
    color: "#6B7280",
    textDecoration: "none",
    fontSize: "12px",
    fontWeight: "500",
  },
  "& .rbc-header.rbc-today a": { color: "#4F46E5", fontWeight: "600" },

  "& .rbc-month-view": { border: "none", flex: 1 },
  "& .rbc-month-row": { borderTop: "1px solid #E5E7EB", minHeight: "90px" },
  "& .rbc-day-bg": { borderLeft: "1px solid #E5E7EB" },
  "& .rbc-day-bg:first-of-type": { borderLeft: "none" },
  "& .rbc-today": { bg: "#EEF2FF" },
  "& .rbc-off-range-bg": { bg: "#F9FAFB" },
  "& .rbc-date-cell": {
    px: "10px",
    py: "6px",
    textAlign: "left",
    fontSize: "12px",
    color: "#6B7280",
  },
  "& .rbc-date-cell a": {
    color: "#6B7280",
    textDecoration: "none",
    _hover: { color: "#111827" },
  },
  "& .rbc-date-cell.rbc-current a": { color: "#4F46E5", fontWeight: "600" },

  "& .rbc-event": {
    bg: "#EEF2FF",
    border: "none",
    borderRadius: "4px",
    px: "8px",
    py: "2px",
    fontSize: "12px",
    fontWeight: "500",
    color: "#4F46E5",
    cursor: "pointer",
    outline: "none",
    transition: "background 150ms ease",
    _hover: { bg: "#E0E7FF" },
    _focus: { outline: "none", boxShadow: "none" },
  },
  "& .rbc-event.rbc-selected": { bg: "#C7D2FE", color: "#3730A3" },
  "& .rbc-event-label": {
    fontSize: "11px",
    fontWeight: "500",
    color: "#4F46E5",
    mr: "4px",
  },
  "& .rbc-event-content": {
    fontSize: "12px",
    fontWeight: "500",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  "& .rbc-show-more": {
    fontSize: "11px",
    color: "#6B7280",
    bg: "transparent",
    px: "8px",
    fontWeight: "500",
    cursor: "pointer",
    _hover: { color: "#4F46E5" },
  },

  "& .rbc-time-view": {
    border: "none",
    flex: 1,
    display: "flex",
    flexDirection: "column",
  },
  "& .rbc-time-header": { borderBottom: "1px solid #E5E7EB" },
  "& .rbc-time-header-content": { borderLeft: "1px solid #E5E7EB" },
  "& .rbc-timeslot-group": {
    borderBottom: "1px solid #E5E7EB",
    minHeight: "60px",
  },
  "& .rbc-day-slot .rbc-time-slot": { borderTop: "1px solid #F3F4F6" },
  "& .rbc-time-slot": { fontSize: "11px", color: "#9CA3AF" },
  "& .rbc-time-column.rbc-today": { bg: "#EEF2FF" },
  "& .rbc-day-slot .rbc-event": {
    bg: "#EEF2FF",
    borderLeft: "3px solid #4F46E5",
    borderRadius: "4px",
    px: "8px",
    py: "4px",
    color: "#4F46E5",
    _hover: { bg: "#E0E7FF" },
  },
  "& .rbc-day-slot .rbc-event.rbc-selected": { bg: "#C7D2FE" },
  "& .rbc-label": { fontSize: "11px", color: "#9CA3AF", pr: "10px" },
  "& .rbc-current-time-indicator": { bg: "#4F46E5", height: "2px" },
  "& .rbc-day-slot": {
    border: "1px solid #E5E7EB",
    borderRadius: "8px",
    overflow: "hidden",
  },

  "& .rbc-overlay": {
    bg: "white",
    border: "1px solid #E5E7EB",
    borderRadius: "10px",
    boxShadow: "0 4px 16px rgba(0, 0, 0, 0.08)",
    p: "10px",
    zIndex: 100,
  },
  "& .rbc-overlay-header": {
    fontSize: "12px",
    fontWeight: "600",
    color: "#111827",
    pb: "8px",
    borderBottom: "1px solid #E5E7EB",
    mb: "8px",
  },
};
